import { ChevronRight, ArrowUpRight, Receipt, Droplets, KeyRound, Wrench, Bell, Car } from 'lucide-react';
import type { UserProfile, Outage, Ticket, Bill, ParkingPass } from '../types';
import { serviceGroups } from '../lib/services';
import type { GroupId, ServiceAction } from '../lib/services';
import { getPassStatus, formatPassDate } from '../lib/parking';
interface Props { profile: UserProfile; outages: Outage[]; tickets: Ticket[]; bills: Bill[]; passes: ParkingPass[]; onAction: (action: ServiceAction) => void; onGroup: (group: GroupId) => void; onPass: (pass: ParkingPass) => void }
export function Dashboard({ profile, outages, tickets, bills, passes, onAction, onGroup, onPass }: Props) {
  const total = bills.filter(b=>b.status !== 'paid').reduce((sum,b)=>sum+b.totalAmount-b.paidAmount,0);
  const outage = outages.find(o=>o.status==='active');
  const activeTickets = tickets.filter(t=>t.apartment===profile.apartment && t.status!=='completed');
  const nextPass = [...passes].filter(p=>['active','scheduled'].includes(getPassStatus(p))).sort((a,b)=>new Date(a.validFrom).getTime()-new Date(b.validFrom).getTime())[0];
  const shortcuts = [{title:'Квитанции',icon:Receipt,action:'bills',tone:'violet'},{title:'Показания',icon:Droplets,action:'meters',tone:'blue'},{title:'Пропуск',icon:KeyRound,action:'guest-pass',tone:'mint'},{title:'Заявка',icon:Wrench,action:'new-ticket',tone:'amber'}] as const;
  return <div className="space-y-6 animate-emil-in">
    <div><p className="text-xs text-slate-400">Здравствуйте, {profile.name.split(' ')[1] || profile.name}</p><h2 className="mt-1 text-[26px] font-semibold tracking-tight">Всё начинается с дома</h2></div>
    <button onClick={()=>onAction('bills')} className="balance-card w-full text-left"><div className="flex items-center justify-between"><span className="text-xs text-violet-200/80">{total>0 ? 'ЖКУ · к оплате' : 'ЖКУ · всё оплачено'}</span><ArrowUpRight size={18} className="text-violet-200"/></div><div className="mt-3 text-[30px] font-semibold tracking-tight">{total.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} <span className="text-xl text-violet-200">₽</span></div><div className="mt-2 text-xs text-violet-200/80">{total>0 ? 'Посмотреть квитанции' : 'Квитанции и история платежей'}</div></button>
    <div className="grid grid-cols-4 gap-2">{shortcuts.map(s=><button key={s.action} className="quick-action" onClick={()=>onAction(s.action)}><span className={`service-icon ${s.tone}`}><s.icon size={22}/></span><span>{s.title}</span></button>)}</div>
    {outage && <button onClick={()=>onAction('outages')} className="notice-row"><Bell size={18} className="shrink-0 text-amber-300"/><span className="min-w-0 flex-1 text-left"><span className="block text-xs font-medium text-amber-100 line-clamp-1">{outage.title}</span><span className="mt-1 block text-[11px] text-slate-400">{outage.period}</span></span><ChevronRight size={16} className="shrink-0 text-slate-500"/></button>}
    <section><div className="mb-3 flex items-center justify-between"><h3 className="section-title">Ваши сервисы</h3><button className="text-xs font-medium text-violet-300 py-2" onClick={()=>onAction('services')}>Все сервисы <span aria-hidden="true">→</span></button></div><div className="grid grid-cols-2 gap-3">{serviceGroups.map(g=><button key={g.id} onClick={()=>onGroup(g.id)} className="category-tile"><span className={`service-icon ${g.tone}`}><g.icon size={22}/></span><h3>{g.title}</h3><p>{g.subtitle}</p></button>)}</div></section>
    {nextPass && <button className="surface flex w-full items-center gap-3 p-4 text-left" onClick={()=>onPass(nextPass)}><span className="service-icon mint"><KeyRound size={20}/></span><span className="min-w-0 flex-1"><span className="block text-xs text-slate-400">{getPassStatus(nextPass)==='scheduled'?'Гость приедет':'Пропуск действует'}</span><span className="mt-1 block text-sm font-semibold">{nextPass.guestCarNumber}</span><span className="mt-1 block text-xs text-slate-400">{formatPassDate(nextPass.validFrom)}</span></span><ChevronRight size={17} className="text-slate-500"/></button>}
    <section><h3 className="section-title mb-3">Под рукой</h3><div className="surface overflow-hidden"><button className="service-row" onClick={()=>onAction('parking')}><Car size={20} className="text-slate-400"/><span className="flex-1 text-left text-sm">Моя парковка</span><span className="text-xs text-slate-400">{profile.parkingSpot.split(' ')[0]}</span><ChevronRight size={16} className="text-slate-500"/></button><button className="service-row" onClick={()=>onAction('tickets')}><Wrench size={20} className="text-slate-400"/><span className="flex-1 text-left text-sm">Мои обращения</span><span className="text-xs text-slate-400">{activeTickets.length ? `${activeTickets.length} в работе` : 'Все заявки'}</span><ChevronRight size={16} className="text-slate-500"/></button></div></section>
  </div>;
}
