import { useState } from 'react';
import { Car, Plus, ChevronRight, KeyRound } from 'lucide-react';
import type { UserProfile, ParkingPass } from '../types';
import { getPassStatus, passLabels, formatPassDate } from '../lib/parking';
export function ParkingView({ profile, passes, onCreate, onOpen }: { profile: UserProfile; passes: ParkingPass[]; onCreate: () => void; onOpen: (pass: ParkingPass) => void }) {
  const [archive, setArchive] = useState(false);
  const visible = passes.filter(p=>archive === ['expired','cancelled'].includes(getPassStatus(p)));
  const currentCount = passes.filter(p=>['active','scheduled'].includes(getPassStatus(p))).length;
  return <div className="space-y-5 animate-emil-in">
    <div><h2 className="page-title">Парковка и пропуска</h2><p className="page-subtitle">Ваше место и гости — в одном разделе</p></div>
    <div className="surface p-4"><div className="flex items-center gap-3"><span className="service-icon mint"><Car size={23}/></span><div><p className="text-xs text-slate-400">Ваше машиноместо</p><p className="mt-1 text-2xl font-semibold">{profile.parkingSpot.split(' ')[0]}</p></div><span className="ml-auto rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] text-emerald-300">Закреплено</span></div><p className="mt-3 text-xs text-slate-400">{profile.parkingSpot.replace(/^\S+\s*/, '').replace(/[()]/g,'')}</p><details className="mt-3 border-t border-white/5 pt-3"><summary className="cursor-pointer text-xs text-slate-300">Мои автомобили · {profile.registeredCars.length}</summary><div className="mt-3 flex flex-wrap gap-2">{profile.registeredCars.map(car=><span key={car} className="rounded-lg bg-white/5 px-3 py-2 font-mono text-xs">{car}</span>)}</div></details></div>
    <button className="primary-button w-full" onClick={onCreate}><Plus size={18}/>Оформить пропуск</button>
    <section><div className="mb-3 flex items-center justify-between"><h3 className="section-title">Мои пропуска</h3><span className="text-xs text-slate-500">{currentCount} актуальных</span></div><div className="segmented-control mb-4"><button aria-pressed={!archive} onClick={()=>setArchive(false)}>Актуальные</button><button aria-pressed={archive} onClick={()=>setArchive(true)}>Архив</button></div><div className="space-y-3">{visible.map(pass=>{const status=getPassStatus(pass);return <button key={pass.id} onClick={()=>onOpen(pass)} className="surface w-full p-4 text-left"><div className="mb-3 flex items-center justify-between gap-2"><span className={`pass-status ${status}`}>{passLabels[status]}</span><ChevronRight size={16} className="text-slate-500"/></div><p className="font-mono text-lg font-semibold">{pass.guestCarNumber}</p><p className="mt-1 truncate text-xs text-slate-400">{pass.guestName}</p><div className="mt-3 border-t border-white/5 pt-3 text-xs text-slate-300">{formatPassDate(pass.validFrom)} → {formatPassDate(pass.validUntil)}</div></button>})}{!visible.length && <div className="surface px-5 py-8 text-center"><KeyRound size={28} className="mx-auto mb-3 text-slate-500"/><p className="text-sm font-medium">{archive?'Архив пока пуст':'Ждёте гостей?'}</p><p className="mx-auto mt-2 max-w-64 text-xs leading-relaxed text-slate-400">{archive?'Здесь будут завершённые и отменённые пропуска.':'Оформите пропуск на нужную дату. Он сохранится здесь и будет всегда под рукой.'}</p></div>}</div></section>
  </div>;
}
